/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface CustomField { 'value' : string, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface ProductivityTrend {
  'period' : string,
  'tasksCompleted' : bigint,
  'averageCompletionTime' : bigint,
}
export interface Project {
  'id' : string,
  'creator' : Principal,
  'name' : string,
  'description' : string,
}
export type RecurrenceFrequency = { 'monthly' : bigint } |
  { 'daily' : bigint } |
  { 'weekly' : bigint };
export interface RecurringTask {
  'frequency' : RecurrenceFrequency,
  'nextOccurrence' : Time,
}
export interface Report {
  'completionRate' : bigint,
  'onTimeDeliveryPercentage' : bigint,
  'productivityTrends' : Array<ProductivityTrend>,
  'averageTaskDuration' : bigint,
}
export type RoleType = { 'admin' : null } |
  { 'teacher' : null };
export interface Task {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'submissionTimestamp' : [] | [Time],
  'recurring' : [] | [RecurringTask],
  'dueDate' : Time,
  'description' : string,
  'customFields' : Array<CustomField>,
  'progress' : bigint,
  'reminderDate' : Time,
  'projectId' : string,
  'dependencies' : Array<string>,
  'priority' : TaskPriority,
  'comments' : Array<Comment>,
  'attachments' : Array<ExternalBlob>,
  'timeEntries' : Array<TimeEntry>,
  'assignedEmployee' : Principal,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TaskTemplate {
  'id' : string,
  'title' : string,
  'description' : string,
  'customFields' : Array<CustomField>,
  'priority' : TaskPriority,
}
export type Time = bigint;
export interface TimeEntry {
  'startTime' : Time,
  'duration' : [] | [bigint],
  'endTime' : [] | [Time],
  'user' : Principal,
}
export interface UserProfile {
  'roleType' : RoleType,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTaskAttachment' : ActorMethod<[string, ExternalBlob], undefined>,
  'addTaskComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string, string], undefined>,
  'createTask' : ActorMethod<
    [
      string,
      string,
      string,
      Principal,
      Time,
      string,
      Time,
      TaskPriority,
      Array<string>,
      [] | [RecurringTask],
      Array<CustomField>,
    ],
    undefined
  >,
  'createTaskTemplate' : ActorMethod<
    [string, string, string, TaskPriority, Array<CustomField>],
    undefined
  >,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTaskTemplates' : ActorMethod<[], Array<TaskTemplate>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAssignedTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProjectReport' : ActorMethod<[], Report>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRoleType' : ActorMethod<[Principal, RoleType], undefined>,
  'startTaskTimer' : ActorMethod<[string], undefined>,
  'stopTaskTimer' : ActorMethod<[string], undefined>,
  'submitWorkForTask' : ActorMethod<[string], undefined>,
  'updateTaskProgress' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];