/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const RecurrenceFrequency = IDL.Variant({
  'monthly' : IDL.Nat,
  'daily' : IDL.Nat,
  'weekly' : IDL.Nat,
});
export const RecurringTask = IDL.Record({
  'frequency' : RecurrenceFrequency,
  'nextOccurrence' : Time,
});
export const CustomField = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const TaskTemplate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'customFields' : IDL.Vec(CustomField),
  'priority' : TaskPriority,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const TimeEntry = IDL.Record({
  'startTime' : Time,
  'duration' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Opt(Time),
  'user' : IDL.Principal,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'submissionTimestamp' : IDL.Opt(Time),
  'recurring' : IDL.Opt(RecurringTask),
  'dueDate' : Time,
  'description' : IDL.Text,
  'customFields' : IDL.Vec(CustomField),
  'progress' : IDL.Nat,
  'reminderDate' : Time,
  'projectId' : IDL.Text,
  'dependencies' : IDL.Vec(IDL.Text),
  'priority' : TaskPriority,
  'comments' : IDL.Vec(Comment),
  'attachments' : IDL.Vec(ExternalBlob),
  'timeEntries' : IDL.Vec(TimeEntry),
  'assignedEmployee' : IDL.Principal,
});
export const RoleType = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'roleType' : RoleType,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const ProductivityTrend = IDL.Record({
  'period' : IDL.Text,
  'tasksCompleted' : IDL.Nat,
  'averageCompletionTime' : IDL.Nat,
});
export const Report = IDL.Record({
  'completionRate' : IDL.Nat,
  'onTimeDeliveryPercentage' : IDL.Nat,
  'productivityTrends' : IDL.Vec(ProductivityTrend),
  'averageTaskDuration' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTaskAttachment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addTaskComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        Time,
        IDL.Text,
        Time,
        TaskPriority,
        IDL.Vec(IDL.Text),
        IDL.Opt(RecurringTask),
        IDL.Vec(CustomField),
      ],
      [],
      [],
    ),
  'createTaskTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TaskPriority, IDL.Vec(CustomField)],
      [],
      [],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTaskTemplates' : IDL.Func([], [IDL.Vec(TaskTemplate)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProjectReport' : IDL.Func([], [Report], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRoleType' : IDL.Func([IDL.Principal, RoleType], [], []),
  'startTaskTimer' : IDL.Func([IDL.Text], [], []),
  'stopTaskTimer' : IDL.Func([IDL.Text], [], []),
  'submitWorkForTask' : IDL.Func([IDL.Text], [], []),
  'updateTaskProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RecurrenceFrequency = IDL.Variant({
    'monthly' : IDL.Nat,
    'daily' : IDL.Nat,
    'weekly' : IDL.Nat,
  });
  const RecurringTask = IDL.Record({
    'frequency' : RecurrenceFrequency,
    'nextOccurrence' : Time,
  });
  const CustomField = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const TaskTemplate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'customFields' : IDL.Vec(CustomField),
    'priority' : TaskPriority,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const TimeEntry = IDL.Record({
    'startTime' : Time,
    'duration' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Opt(Time),
    'user' : IDL.Principal,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'submissionTimestamp' : IDL.Opt(Time),
    'recurring' : IDL.Opt(RecurringTask),
    'dueDate' : Time,
    'description' : IDL.Text,
    'customFields' : IDL.Vec(CustomField),
    'progress' : IDL.Nat,
    'reminderDate' : Time,
    'projectId' : IDL.Text,
    'dependencies' : IDL.Vec(IDL.Text),
    'priority' : TaskPriority,
    'comments' : IDL.Vec(Comment),
    'attachments' : IDL.Vec(ExternalBlob),
    'timeEntries' : IDL.Vec(TimeEntry),
    'assignedEmployee' : IDL.Principal,
  });
  const RoleType = IDL.Variant({ 'admin' : IDL.Null, 'teacher' : IDL.Null });
  const UserProfile = IDL.Record({
    'roleType' : RoleType,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const ProductivityTrend = IDL.Record({
    'period' : IDL.Text,
    'tasksCompleted' : IDL.Nat,
    'averageCompletionTime' : IDL.Nat,
  });
  const Report = IDL.Record({
    'completionRate' : IDL.Nat,
    'onTimeDeliveryPercentage' : IDL.Nat,
    'productivityTrends' : IDL.Vec(ProductivityTrend),
    'averageTaskDuration' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTaskAttachment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addTaskComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          Time,
          IDL.Text,
          Time,
          TaskPriority,
          IDL.Vec(IDL.Text),
          IDL.Opt(RecurringTask),
          IDL.Vec(CustomField),
        ],
        [],
        [],
      ),
    'createTaskTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TaskPriority, IDL.Vec(CustomField)],
        [],
        [],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTaskTemplates' : IDL.Func([], [IDL.Vec(TaskTemplate)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProjectReport' : IDL.Func([], [Report], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRoleType' : IDL.Func([IDL.Principal, RoleType], [], []),
    'startTaskTimer' : IDL.Func([IDL.Text], [], []),
    'stopTaskTimer' : IDL.Func([IDL.Text], [], []),
    'submitWorkForTask' : IDL.Func([IDL.Text], [], []),
    'updateTaskProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };